### ISSUE TITLE
Créer des tuiles pour tous les thèmes

### ISSUE THREAD

**Issue by gjuchault** [Insoumis/analysons-lepen#6]
Passer de ça:
![image](https://cloud.githubusercontent.com/assets/678848/25897370/0ab4ea78-3588-11e7-8f4b-bb97c0c62cde.png)
à ça : http://codepen.io/anon/pen/eWVMNx

**Comment by Asenar** [comment]
Et pour les photos à utiliser, c'est à discrétion du développeur ou les trucs sont déjà définis ?
